type: "jenkins"
server:
  host: 0.0.0.0
  port: 8080

db:
  postgres:
    host:
    port:
    username:
    password:
    dbname:

jenkins:
  url: "http://jenkins-dev.devops.wise-paas.com"
  username: "codetest"
  password: "P@ssw0rd"

tekton:
  url: ""
